### ISSUE TITLE
Error with 2.5 and Gzdoom 4.9.0

### ISSUE THREAD

**Issue by Skrell** [SnakieJakie/More-Lights#1]
Script error, "morelights2.5_base.pk3:gllumps/glowflats/realmstuff/dtexpak" line 33:
Missing string (unexpected end of file).

Running this with BTSX E1 btw in case that matters.  Also 2.4 works fine.

**Comment by SnakieJakie** [comment]
Try re-downloading, when 2.5 first came out, there was a similar sounding issue that was fixed right away.

**Comment by Skrell** [comment]
Yep that was it!  Great work btw I LOVE this mod!

**Comment by SnakieJakie** [comment]
Glad it worked! Thank you!
